export const GO_SEARCH = "GO_SEARCH";
export const RECEIVE_SEARCH = "RECEIVE_SEARCH";
export const CHANGE_RESULTS_MODE = "CHANGE_RESULTS_MODE";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
